/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppBulletinDismissals {
  bulletin_id: string;
  created_at: Timestamp;
  id: Generated<string>;
  viewer_id: string;
}

export interface AppBulletinReports {
  bulletin_id: string;
  created_at: Timestamp;
  id: Generated<string>;
  reporter_id: string;
}

export interface AppBulletins {
  /**
   * NULL means live. Archived bulletins are absent from app.visible_bulletins for everyone, author included; the author keeps them through bulletins.listMine, which reads this table by author_id (M2-AC12).
   */
  archived_at: Timestamp | null;
  author_id: string;
  body: string;
  created_at: Timestamp;
  id: Generated<string>;
  search_document: Generated<string | null>;
  title: string;
  type: string;
  /**
   * ADR-0005 optimistic-concurrency version. Unused by M2's two mutations (both `expectedVersion: no`); required so bulletin.update (M5) has a version to compare.
   */
  version: Generated<number>;
}

export interface AppConnections {
  /**
   * What user A grants user B: full | limited. Consumed by app.visible_people, which fails closed — anything that is not exactly full is topology_only.
   */
  a_discloses_to_b_level: Generated<string>;
  b_discloses_to_a_level: Generated<string>;
  created_at: Timestamp;
  id: Generated<string>;
  status: string;
  user_a_id: string;
  user_b_id: string;
}

export interface AppConnectionTrust {
  owner_id: string;
  subject_id: string;
  trust: number | null;
  updated_at: Timestamp;
}

export interface AppConsumerReceipts {
  consumer_name: string;
  event_id: string;
  processed_at: Timestamp;
}

export interface AppInvitations {
  accepted_at: Timestamp | null;
  accepted_by_id: string | null;
  created_at: Timestamp;
  id: Generated<string>;
  inviter_id: string;
  revoked_at: Timestamp | null;
  /**
   * pending | accepted | revoked. Deliberately no check constraint, matching app.users.status: an unrecognised value must fail CLOSED in the application (nothing but pending can be opened or accepted) rather than loudly in a constraint the reader has to go find.
   */
  status: Generated<string>;
  token: string;
}

export interface AppMutationResults {
  /**
   * Namespaces every mutation_id lookup (ADR-0005): one actor can neither probe nor collide with another actor's mutation IDs, even though the primary key alone is global.
   */
  actor_id: string;
  /**
   * Has a default, unlike app.bulletins.created_at and app.invitations.created_at: ADR-0005's schema block specifies `default now()` for this column explicitly, and it is a bookkeeping timestamp for the 30-day retention window (ADR-0005), not a product fact a writer states.
   */
  created_at: Generated<Timestamp>;
  mutation_id: string;
  mutation_type: string;
  outcome: string;
  request_hash: string;
  result: Json | null;
}

export interface AppOutboxEvents {
  actor_id: string | null;
  aggregate_id: string;
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  event_id: string;
  event_type: string;
  event_version: Generated<number>;
  last_error: string | null;
  occurred_at: Timestamp;
  payload: Json;
  status: Generated<string>;
}

export interface AppUsers {
  auth_user_id: string;
  avatar_path: string | null;
  /**
   * No default, on purpose (ADR-0008:29): the writer states when onboarding completed rather than inheriting whatever the row happened to be inserted at.
   */
  created_at: Timestamp;
  deactivated_at: Timestamp | null;
  display_name: string;
  erased_at: Timestamp | null;
  /**
   * citext, so uniqueness is case-insensitive without a functional index. The remaining handle rules (charset, length, reserved words, confusables, immutability) live in modules/identity/domain/handle.policy.ts — this column enforces the one rule a database can enforce (ADR-0008:50-57).
   */
  handle: string;
  id: Generated<string>;
  status: Generated<string>;
  version: Generated<number>;
}

export interface DB {
  "app.bulletin_dismissals": AppBulletinDismissals;
  "app.bulletin_reports": AppBulletinReports;
  "app.bulletins": AppBulletins;
  "app.connection_trust": AppConnectionTrust;
  "app.connections": AppConnections;
  "app.consumer_receipts": AppConsumerReceipts;
  "app.invitations": AppInvitations;
  "app.mutation_results": AppMutationResults;
  "app.outbox_events": AppOutboxEvents;
  "app.users": AppUsers;
}
